[package]
name = "shorty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
actix-web = "4.0.0-beta.21"
sqlx = { version = "0.5.1", features = ["runtime-tokio-rustls", "chrono", "migrate", "offline", "macros"] }
